#!bin/bash
#Este scrip tiene la finalidad de instalar blast desde biocontainers y probarlo con un ejemplo entre humano y pez cebra


#ubicarse en el directorio datos_blast dentro del Escritorio
cd /home/mel/Escritorio; mkdir datos_blast ; cd datos_blast

#Instalar BLAST desde biocontainers
docker pull biocontainers/blast

#Correr BLAST
docker run biocontainers/blast blastp -help

#Descargar la secuencia FASTA de prion humano desde UniProt 
wget http://www.uniprot.org/uniprot/P04156.fasta

#Descargar la base de datos de pez cebra
curl -O ftp://ftp.ncbi.nih.gov/refseq/D_rerio/mRNA_Prot/zebrafish.1.protein.faa.gz
gunzip zebrafish.1.protein.faa.gz

#Preparar la base de datos para hacer el blast y montar el volumen 
sudo docker run -v /home/mel/Escritorio/datos_blast:/data/ biocontainers/blast makeblastdb -in zebrafish.1.protein.faa -dbtype prot

#Obtener las alineaciones finales 
sudo docker run -v /home/mel/Escritorio/datos_blast:/data biocontainers/blast blastp -query P04156.fasta -db zebrafish.1.protein.faa -out results.txt



